### ISSUE TITLE
Allow multiple namespaces where ever the -n option exists

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#1058]
My scripts on SMI-S mocks currently have just one namespace. In order to change to multiple namespaces, I would have to redesign the scripts to issues commands multiple times to get all the instances I am looking for. I would like to be able to specify multiple default namespaces to avoid the massive change to my scripts.

I have an alternate suggestion, use the find command that finds instances and classes across single, multiple, or all namespaces.  This would add a --detail option that would display the same display as the enumerate output.

Thus, class find CIM_blah --detail would show the table and then the MOF for the instances in each namespace.

The instance count CIM_blah* --detail would show the table with the counts and then the MOF.

**Comment by KSchopmeyer** [comment]
Karl - Finalize if we can do anything for this

**Comment by KSchopmeyer** [comment]
We are concerned that we may implement something and it does not even solve the problem Mike has.  We propose to exactly show Mike what we propose and see if that clarifies if it solves his problem or not.

Next meeting with Mike about 7 Jan 2022.

Action Karl

**Comment by KSchopmeyer** [comment]
Comment from Mike that there are user cases where use of classes crosses multiple providers and it can be very useful for users to see the instances of one or more class across multiple namespaces where the providers are implemented.

This makes sense.

**Comment by KSchopmeyer** [comment]
We need to define this so it is consistent across all the commands and should encompass also the class find and instance count.

**Comment by KSchopmeyer** [comment]
Karl will define the proposal and we can bring back for discussion then.  Discussion removed

**Comment by KSchopmeyer** [comment]
Proposal:

The proposal is to extend commands that use the --namespace command option so that they can return results for multiple namespaces.

The commands affected are the enumerate, get, associators, references commands for classes, instances and qualifier declarations.  

In each case, the --namespace option would be extended to allow multiple namespaces to be defined for the command using a combination of the use of the "multiple' with the option and also the possibility for the user to supply multiple namespace with a comma-separated string defining multiple namespaces.

Thus, for example, the class enumerate could:

1. execute exactly as it currently does with either
    a. no namespace provided so that the connection default_namespace would be used.
    b. a single namespace (ex. --namespace interop)

2. Handle multiple namespaces in a single command by extending the --namespace to allow multiple namespaces as either:
   a. repeated definition of the --namespace option (i.e. multiple) (ex. -n interop -n root/cimv2)
   b. Extension of the processing to allow multiple namespace definitions in a single option definition by handling a comma-separate list of namespace names (ex. --namespace interop,root/cimv2)
    c. multiple namespaces (ex. --namespace interop, --namespace root/cimv2) or (ex. class enumerate --namespace interop, root/cimv2)

3. The default if the command --namespace option is not provides will continue to be the existing namespace.

The real issue is not processing multiple namespaces to get the requested classes, class names, instances, instance names, or qualifierdecls but extending the output form that provides information similar to the existing output for all of the ouput format types for these commands (mof, table, text) when no or one namespace is provided but extended to be able to associate each result with its namespace if multiple namespaces are defined.

**Comment by KSchopmeyer** [comment]
| output object |  output format | status today  | Proposed changes |
| ---- | ---- | ---- | ---- |
| class | mof  | No ns info   |    |
| class | table  | no ns info  |    |
| class | text  | TODO  |    |
| class name | mof | no ns info   |   |
| class name | table | no ns info   |   |
| class name | text | TODO  |   |
| instance |  mof | no ns info   |   |
| instance | table | no ns info   |   |
| instance name |  mof | Ns in each object |   |
| instance name |  table | Ns in each object |  
| instance name |  txt | TODO |   |
| qualdecl |  Table |  No ns info  |  |
| ---- |---- |---- | --- |

**Comment by KSchopmeyer** [comment]
Examples of current output:
## enumerate class names
pywbemcli> class enumerate --no --di --namespace interop
```
CIM_Namespace
CIM_ObjectManager
```
pywbemcli> -o table class enumerate --no --di --namespace interop
```
Classnames:
+-------------------+
| Class Name        |
|-------------------|
| CIM_Namespace     |
| CIM_ObjectManager |
+-------------------+
```
## Enumerate instance names

pywbemcli> -o table instance enumerate CIM_Foo --no --di
```
InstanceNames: CIM_Foo
+--------+-------------+-----------------+------------------+
| host   | namespace   | class           | key=             |
|        |             |                 | InstanceID       |
|--------+-------------+-----------------+------------------|
|        | root/cimv2  | CIM_Foo         | CIM_Foo1         |
|        | root/cimv2  | CIM_Foo         | CIM_Foo2         |
|        | root/cimv2  | CIM_Foo         | CIM_Foo3         |
|        | root/cimv2  | CIM_Foo         | CIM_Foo30        |
|        | root/cimv2  | CIM_Foo         | CIM_Foo31        |
|        | root/cimv2  | CIM_Foo_sub     | CIM_Foo_sub1     |
|        | root/cimv2  | CIM_Foo_sub     | CIM_Foo_sub2     |
|        | root/cimv2  | CIM_Foo_sub     | CIM_Foo_sub3     |
|        | root/cimv2  | CIM_Foo_sub     | CIM_Foo_sub4     |
|        | root/cimv2  | CIM_Foo_sub_sub | CIM_Foo_sub_sub1 |
|        | root/cimv2  | CIM_Foo_sub_sub | CIM_Foo_sub_sub2 |
|        | root/cimv2  | CIM_Foo_sub_sub | CIM_Foo_sub_sub3 |
+--------+-------------+-----------------+------------------+
```

pywbemcli> instance enumerate CIM_Foo --no --di

```
root/cimv2:CIM_Foo.InstanceID="CIM_Foo1"
root/cimv2:CIM_Foo.InstanceID="CIM_Foo2"
root/cimv2:CIM_Foo.InstanceID="CIM_Foo3"
root/cimv2:CIM_Foo.InstanceID="CIM_Foo30"
root/cimv2:CIM_Foo.InstanceID="CIM_Foo31"
root/cimv2:CIM_Foo_sub.InstanceID="CIM_Foo_sub1"
root/cimv2:CIM_Foo_sub.InstanceID="CIM_Foo_sub2"
root/cimv2:CIM_Foo_sub.InstanceID="CIM_Foo_sub3"
root/cimv2:CIM_Foo_sub.InstanceID="CIM_Foo_sub4"
root/cimv2:CIM_Foo_sub_sub.InstanceID="CIM_Foo_sub_sub1"
root/cimv2:CIM_Foo_sub_sub.InstanceID="CIM_Foo_sub_sub2"
root/cimv2:CIM_Foo_sub_sub.InstanceID="CIM_Foo_sub_sub3"
```
