### ISSUE TITLE
Show namespace on display of classes and instances

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#1059]
It would be nice to display the namespace a class or instance is in when displaying them in mof or table format.

**Comment by KSchopmeyer** [comment]
Do you mean the namespace or the path.  Since you request the display of classes or instances by namespace (Either the default namespace or the namespace specified by the command option --namespace, you do know the namespace.   Since, the issue appears to be one of trying to see multiple cim objects as they appear in different namespaces per discussion with Mike, I wonder if just extending the find class and count instance commands with an option such as --detail so that they would display the mof output for the items found as opposed to just the namespaces in which they occur and counts for instances.

Thus, class find CIM_blah --detail would show the table and then the mof for the instances in each namespace.

The instance count CIM_blah* --detail would show the table with the counts and then the MOF.

**Comment by andy-maier** [comment]
In MOF format, the namespace could be shown as a pragma namespace.

**Comment by KSchopmeyer** [comment]
Note: There is a real issue with the use of the namespace pragma.  At least OpenPegasus never implemented this pragma so any mof we generated from pywbemcli would never be compiled with the OpenPegasus compiler.

**Comment by KSchopmeyer** [comment]
There are several possibilities:

Karl will present some proposals to Mike
