### ISSUE TITLE
Test approach does not deal with reordered XML attributes

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#1173]
XML attributes can appear in any order. However, our tests check returned CIM-XML by comparing strings, which assume a certain order of the XML attributes.

Here is one recent occurrence where that test approach fails:

* https://github.com/pywbem/pywbemtools/runs/6143973332?check_suite_focus=true

The error happens only on Python 3.6 and 3.7, but on all OSs and with both package levels

One option would be to compare XML as an XML tree representation, e.g. using ElementTree.

**Comment by andy-maier** [comment]
The idea is to leave the XML strings stored as strings, and only change the comparison to be done at the XML representation level.

**Comment by KSchopmeyer** [comment]
Note that starting with Python 3.8, the minidom toprettyxml() method preserves the attribute order specified by the user.  However, with earlier versions of XML, that is not the case. Thus the ordering problem

The issue occurs because we actually have only a minimum of tests of the XML output of classes and that is the one output where this variability occurs.  There are no qualifiers in instances. Since we are using the toprettyxml() method, to map the XML representation of the qualifier to a string, there is not much we can do about the ordering of the attributes.

**Comment by KSchopmeyer** [comment]
We will not fix the issue of unordered qualifier attributes in pywbem since that is a python issue that only applies to python versions <= 3.7 but just fix the tests.
