### ISSUE TITLE
Add xonsh shell support

### ISSUE THREAD

**Issue by anki-code** [pywbem/pywbemtools#1290]
Hi! Thanks for the awesome tools!
Please add [xonsh shell](https://xon.sh) support.
Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by KSchopmeyer** [comment]
We have a problem with that since we today depend on the support supplied by the python click package that is the core of command definition, etc. for pywbemtools.  It is also the source of the scripts that we call the complete scripts and they only provide scripts for bash, zsh, and fish.

However, you are not the only other shell we want to support for tab-completion. so we are keeping this request open pending some research on what needs to be done to support xonsh tab-completion.

**Comment by KSchopmeyer** [comment]
Marking closed since there is no incication that the click package itself will support additional shells and the tab completion for shells is based on click defining a tab-completion function for each shell type supported.
