### ISSUE TITLE
Formatting of click help in options

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#176]
The formatting of bulleted lists in the help parameter of click options does not create a clean output.  It appears to cut the lines off short and I have not found a way to create clean indented bulleted test.

Thus, the text of one example looks like:

```
                                  - Scheme: must be "https" or "http"
                                  [Default: "https"].
                                  - Host: defines short or
                                  fully qualified DNS hostname, a literal IPV4
                                  address (dotted) or a literal IPV6 address.
                                  - Port: (optional) defines WBEM server port
                                  to be used [Defaults:5988(HTTP) and 5989
                                  (HTTPS)].

```
where we want it to look like:

```
                                  -  Scheme: must be "https" or "http"
                                     [Default: "https"].
                                  -  Host: defines short or fully qualified DNS
                                     hostname, a literal IPV4 address (dotted)
                                     or a literal IPV6 address.
                                  -  Port: (optional) defines WBEM server port
                                     to be used [Defaults:5988(HTTP) and 
                                     5989(HTTPS)].

**Comment by KSchopmeyer** [comment]
Move to 0.6.0 since this should be considered minor, (no loss of information)

**Comment by andy-maier** [comment]
Here are the options I could come up with:

1. Use `\b` which disables the reformatting of the paragraph. Paragraphs in this definition are separated by empty lines (i.e. 2x newline). The disadvantage of this approach is that this disables any formatting, so once we start supporting a wider output (e.g. adjusted to the current terminal width), the manual formatting of any option using `\b` will not automatically adjust its width.

2. Write a custom help formatter in click. That is not documented in the click docs, and besides a formatter for the epilog (https://stackoverflow.com/a/42489610/1424462) I could not find any examples. It is probably possible. The question is, is it worth it. The only help text that would benefit from it is the help text of the `--server` option, and that one has already been changed since this issue was created to fit into one wrapped paragraph. I think that is good enough.

**Discussion point:** I suggest to close this issue as "won't implement"

**Comment by KSchopmeyer** [comment]
Agreed to close wont fix.
