### ISSUE TITLE
Final issues for release of pywbemtools 0.5.0

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#191]
1. Review and clean up the README.rst file.
    Status: DONE. PR #195 addresses some issues. Andy has provided more review comments, below.

2. Add pywbem version to the display of the --version subcommand.
    Status: DONE in PR #197.   

3. Finish documentation update to bring documentation in line with code.
    Status: DONE in PR #162.

4. Add references to documentation where required in help (ex. format for DSP0207 url format.
    Status: Statement inserted into help for each subcommand that uses INSTANCENAME to define the the format as based on WBEM_URI as defined in DMTF DSP0207. PR #190 merged. DONE

5. Refactor code into directory structure with pywbemtools at the top and pywbemcli in pywbemtools.
   Status: DONE. PR #200

Added by Andy:

5. Review and clean up the README_PYPI.rst file.
    Status: DONE. PR xxx

6. Review and update the RTD documentation.
    Status: DONE. PR merged. Andy has provided review comments, below.

7. Review and update pywbemcli help texts. 
    Status: DONE. Several PRs files and approved.

8. Update the DEVELOP.md file
   Status: DONE. Andy has created PR #194 to adjust it to this project.

9. [Mandatory issues for 0.5.0](https://github.com/pywbem/pywbemtools/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22version+0.5.0%22+label%3A%22release%3A+mandatory%22)

**Comment by andy-maier** [comment]
Review of RTD docs:

1. generally on the term "command line browser": I suggest to use "command line interface" instead.

2. main page, on "This package contains tools that use pywbem to implement a command line browser (pywbemcli)": I suggest to split this into a sentence that talks only about the pywbemtools package, and a list with one item for the pywbemcli command, e.g.:

      The pwbewmtools package contains tools that use pywbem:
        * pywbemcli: A command line interface to WBEM servers

3.

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 2):

1. In 2., on "This package provides a command line interface (CLI) in the pywbemcli tool that supports communication with a WBEM server through the pywbem client api and shell scripting.": It supports communication [...] through shell scripting? I think anyone using commands understands that they can write shell scripts around commands. I suggest removing "and shell scripting".

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 2):

1. In 2., on "This package provides a command line interface (CLI) in the pywbemcli tool that supports communication with a WBEM server through the pywbem client api and shell scripting.": It supports communication [...] through shell scripting? I think anyone using commands understands that they can write shell scripts around commands. I suggest removing "and shell scripting", unless you meant to refer to the interactive mode. In which case that term should be used, instead.

2. In 2.2, on "This pywbemcli shell is started when the `pywbemcli` command ...": Here, `pywbemcli` is formatted in monospace font. I think we should be consistent with that. I'm not sure whether I have a strong opinion on the use of monospace formatting, but it should be consistent.

3. In 2.2, on the first two examples: I suggest not to show the meta-syntax of the help in an example. I.e. remove `[GENERAL-OPTIONS]`.

4. In 2.2, Example with `> c --help`: This does not work. Typing a blank after `c` causes the shell to display an exception and never come out of that loop again. I have opened an issue for that. I think the example should be changed to `> class --help`.

5. In 2.3, on "TODO: Need to sort this one out": Bash completion works that way. the TODO can be removed.

6. In 2.4, on "The pywbemcli CLI has environment variable options corresponding to the command line options for specifying the general options to be used including:":
    * On "pywbemcli CLI": We should be consistent with how it is referred to.
    * On "environment variable options": I find this confusing and suggest to remove "options".
    * On "corresponding to the command line options for specifying the general options": I suppose this could be stated simpler, e.g. "corresponding to most of its general command line options".
    * On "including": Use of this word always causes me to suspect that the provided information is not complete. I think we should provide complete information and remove that word.

7. In 2.4, PYWBEMCLI_KEYFILE occurs twice in the list of variables, for different options.

8. In 2.4, PYWBEMCLI_USE_PULL and PYWBEMCLI_PULL_MAX_CNT are the only variables whose suffix after PYWBEMCLI_ is not exactly the long option name. It would be nice if that could be consistent. Maybe change both of these options according to the env var suffixes.

9. In 2.4, on example "`pywbemcli class get CIM_Managed element`": Extra space in the class name: c/CIM_Managed element/CIM_ManagedElement/

10. In 2.4, on "... or entering it on the command line.": The use of "entering" is confusing since the text just talked about password prompting, while this sentence here is meant to avoid that. I suggest to change "entering" to "specifying".

11. In 2.4, on example "`pywbemcli -s http://localhost -n root/cimv2 -u fred`" and several other examples: The option for the default namespace is `-d` and not `-n`. Occurs multiple times.

12. 11. In 2.4, on the two examples that are meant to show the `connection export` command (plain and with eval): That command is missing from the example command lines.

13. In 2.5, on "pywbemccli provides for logging to ...": I suggest to split this sentence into two, one that talks about where it can log to and one that talks about what can be logged.

14. In 2.5, on "The default is no logging if the –logging option  ...": Incorrect name for the option, it is `--log`.

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 3):

1. In 3, first paragraph, on "including the following:": Why are we describing only a small subset of the options?

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 4):

1. In 4, on "Generally the structure of pywbemcli is:"
    * I suggest to rephrase that to "The general command syntax of pywbemcli is:"
    * The command syntax should be in monospace font.
    * The command syntax should be consistent with the usage line shown in the help texts.

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 5):

1. I did not review this, but given that some commands in chapter 4 show a mismatch between docs and actual help, I suppose that some adjustments in chapter 5 would also be needed.

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 6):

1. In 6., on "TODO need more on overview": Write a brief overview on the chapter.

2. In 6.1, on "see TODO for detailed information.": Add link to pywbem chapter on RTD.

3. In 6.1, on "The input parameter _use-pull-ops_ allows ..." and "... by changing a pywbemcli input parameter (use-pull-ops).": Change this to talk about the "command line option `--use-pull-ops`".

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 7):

1. In 7., on "Support for mocking a WBEM server is integrated into pywbemcli using the pywbem `pywbem_mock` subpackage and the pywbemcli `--mock-server` global command line option.": This should be simplified.
  How about: "The pywbem package has support for mocking a WBEM server. This support is integrated into pywbemcli via its `--mock-server` global command line option."?

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 8):

1. On 8.1: None of the special type names is used. The entire section can be removed.

2. On 8.2: Most of the references are not used. I suggest to remove those that are not used.

**Comment by andy-maier** [comment]
Review of RTD docs (chapter 9):

1. On 9.1: Not sure how you look at this, but given that this is the first release, we probably should remove any history and all sub-sections of 9.1, and simply state that this is the first release of the package.

**Comment by andy-maier** [comment]
Review of README file on Github repo:

* buttons are missing
* Installation reqs: Python version is not "3.4 or 3.6", but "3.4 and higher".
* Installation reqs: It is not just Linux, but Linux, MacOS, Windows (native), Windows (CygWin). At least that's what we test.
* Installation: The link to the "Installation section" `http://pywbemtools.readthedocs.io/en/stable/intro.html#installation` is not correct. The "stable" version does not exist yet, but will when it is released. But the file is also not correct. I suggest changing it to `https://pywbemtools.readthedocs.io/en/latest/introduction.html#installation`.

**Comment by andy-maier** [comment]
Everything done, except mandatory issues, which are also listed from within issue #165.
Closing this issue here.
