### ISSUE TITLE
Appveyor fails on native Windows with minimum package level

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#240]
The latest master version fails on Appveyor on all variants with native Windows and package level minimum. See the list of runs of the latest manual-ci-run branch: https://ci.appveyor.com/project/KSchopmeyer/pywbemtools/builds/26788198

It always seems to be the same issue, namely that `assert_rc()` fails with "AssertionError: Unexpected exit code (expected 0, got 1)".

Note that the same Python versions on native Windows succeed with the latest package level, so it must have to do something with the level of dependent packages.

**Comment by KSchopmeyer** [comment]
The issue is specifically the following as far as I can tell:
[00:04:33] stderr = 'Traceback (most recent call last):
[00:04:33]   File "c:\projects\pywbemtools\.tox\win64_py37_64\scripts\pywbemcli-script.py", l...DistributionNotFound: The \'prompt-toolkit<2.0.0,>=1.0.15\' distribution was not found and is required by pywbemtools

which is wierd since it finds that distribution for other tests.  Further, that error occurs on tests with python 3.5, not just the tests with python 2.7 where that rule should be invoked.

There is an error in minimun-constraints in that I specify 2.0.1 as the minimum.

Changing that now.

**Comment by andy-maier** [comment]
Fixed by PR #243.
