### ISSUE TITLE
Inconsistent way connections are named in connection subcommands

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#261]
The subcommands within the `connection` command group are inconsistent in the way the connection is named. I was going by their help text and did not verify whether the actual behavior is as described there.

The following subcommands use an existing connection:

* delete - names the connection via the optional NAME argument. If not specified, it prompts.
* select - names the connection via the optional NAME argument. If not specified, it selects current connection.
* show - names the connection via the optional NAME argument. If not specified, it prompts.
* test - only works on current connection.

The following subcommands create a new connection:

* add - names new connection via required --name subcommand option.
* save - names new connection via optional --name subcommand option, and with a quite complex behavior:
   - If specified, and the current connection was specified using the --name general option, it renames that connection to the name from the --name subcommand option. I consider that a very unexpected side effect of what "save" is otherwise described and/or expected to do.
  - If specified, and the current connection was not specified using the --name general option, it (probably?) creates a new connection with the name from the --name subcommand option.
  - If not specified, it is not clear where the new connection gets its name from (at least if the current connection was specified using --server or --mock-server general option). Remember, the --name general option is mutually exclusive with --server and --mock-server.

The remaining subcommands operate on all connections and do not deal with specifying names.

I suggest that we make it consistent how connections are named.

**Comment by KSchopmeyer** [comment]
1. I specifically wanted show to default to the current connection. Therefore show  has a different default than delete or select both of which take from the connection file as their base of information.  Notice also that show is just text output, not a table or something like a table.

2. Connections from the cmd line now get the name 'default' when created.  You could save one with that name but we wanted the ability to name then what we want so the --name option.

3. save - names new connection via optional --name subcommand option, and with a quite complex behavior:

 * If specified, and the current connection was specified using the --name general option, it renames that connection to the name from the --name subcommand option. I consider that a very unexpected side effect of what "save" is otherwise described and/or expected to do.  **COMMENT**: IU had not thought of that one reading in a connection and naming it something else with save.

* If specified, and the current connection was not specified using the --name general option, it creates a new connection with the name from the --name subcommand option. **COMMENT** That is the normal expected path to create new connections.

 If not specified, it is not clear where the new connection gets its name from (at least if the current connection was specified using --server or --mock-server general option). Remember, the --name general option is mutually exclusive with --server and --mock-server.  **COMMENT**: If no name is specified, the new connection gets the name default. If that name is already used, an exception is generated.  We do not allow rewriting with the name of a connection already in the file at this point. Note that this was not a required behavior. We could just as well allowed rewriting the same connection name either just overwriting or with a confirm prompt. I took the no rewrite approach to keep it simple until someone starts to use it.

**Comment by andy-maier** [comment]
Karl wanted to make a proposal for cleaning this up.

**Comment by andy-maier** [comment]
Karl, on your comments:

* > 1. I specifically wanted show to default to the current connection....

  First, the "select" command is the only one where it defaults to the current connection.

  But let's assume other commands would be changed to also default to the current connection. The problem then is that the current connection does not have a name, unless it was specified using the --name option. So the current connection does not serve well as a default name.

* > 2. Connections from the cmd line now get the name 'default' when created.

  That is not described anywhere, and I see a different description: 
  * "add" requires the `--name` option and uses that as the name of the added connection.
  * "save" is quite complex w.r.t. the name of the saved connection (see my initial comment), and a use of a name "default" does not appear anywhere in the description.

I think we need to discuss:
* Why is there a NAME positional argument at all, instead of working with the --name option?
* Can we agree not to default to the current connection, because that one may not have a name?

**Comment by andy-maier** [comment]
One case that shows the current inconsistency is this attempt to store a mocked connection:
```
$ pywbemcli -m tests/unit/simple_mock_model.mof -n myconn connection add
The --name "myconn" option and --server "(u'tests/unit/simple_mock_model.mof',)" option are mutually exclusive and may not be used simultaneously
Aborted!

$ pywbemcli -m tests/unit/simple_mock_model.mof connection add
Usage: pywbemcli connection add [COMMAND-OPTIONS]
Try "pywbemcli connection add -h" for help.

Error: Missing option "-n" / "--name".
```

**Comment by KSchopmeyer** [comment]
We propose to change the connection file to add one more variable, the current connection flag.  This determines what connection would be automatically used if you do not specify --server --name or --mock-server.

**Comment by KSchopmeyer** [comment]
Extend the add so that we can get get it from a pre-existing name  in additon to a completely new server.

I agree to your proposal on save.

**Comment by KSchopmeyer** [comment]
The proposed changes for the connection add, delete, select, test are:

1. always use the NAME positional argument to name the target connection (instead of the --name option) and in the optional cases default to prompting if not specified?

2. Change the select so that it is persistent and modify the behavior so that if there is no --mock-server, --name, --server general options, pywbemcli tries to use the selected name from the repository file.

3. Extend add with a --name so that we can use an existing names as the basis for a new name.

**Comment by KSchopmeyer** [comment]
**DISCUSSION:** I would like to move one piece of functionality to a separate issue, the option on  connection add where --name becomes the name of a template for the new connection and the options modify that entity.  It is logical except that the current defintion of options is not consistent with using them as modifiers because of the way that use defaults. In this case, you only want to modify connection parameters that have the option set but how do you disable the --noverify with an option since the option is only used if you want to set no-verify True.  It would have to change to an option that sets and unsets so that there are 3 values received by the code (None - do nothing, True - Set it, False Unset it).

**Comment by andy-maier** [comment]
We clarified in the call that `connection add` should use `--name` only as the input that is used unchanged (i.e. cannot be combined with `--server`).

**Comment by andy-maier** [comment]
PR #306 addresses this issue.
