### ISSUE TITLE
Docs: Issues with 4.1. "Pywbemcli special command line features"

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#314]
Section 4.1. "Pywbemcli special command line features" has the following sub-sections:
* 4.1.1. pywbemcli commands to WBEM Operations
* 4.1.2. Displaying CIM instances or CIM instance names
* 4.1.3. Specifying the INSTANCENAME command argument
* 4.1.4. Interactively selecting INSTANCENAME

There are some issues with that:
* Being at the H3 level, they are not visible in the general TOC. That would be good however, for most of them, because they cover topics (I think) the reader is likely to look up again, so TOC visibility would be good.
* It is not clear (to me) what the criteria is by which these sub-sections are under section 4.1 vs being one heading level higher under section 3. Most of them have to do with options as well.

**Comment by andy-maier** [comment]
Karl will think about the proosal to move them one heading level higher into section3.

**Comment by KSchopmeyer** [comment]
I see two alternates: 

1 move them to section 3 but the same argument exists there, why 3 rather than 4.

2. Create a section specifically for this type of material, the features that need specific documentation rather than having that documentation hidden in other sections.  The downside is that they take up a whole section in the TOC.

3. Do them as footnotes/terms/etc. and reference them from where we want to point to them.  The downside of this is that they do not appear in the TOC.

The criteria are that:

1. They be discussion of general features that apply across a broad set of the documentation

2. They Are something we want to point out the reader before they get into details

I propose we go back to a new top level section. Note that at one time these were their own section (section 6) before we put them first in section 4 and then to section 4.

**Comment by andy-maier** [comment]
Addressed by PR #325.
