### ISSUE TITLE
Travis run on OS-X, py3, pkglevel=minimum, takes very long time

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#348]
It comes close to the allotted maximum time of 50min and if it does, the run is terminated by Travis. See for example https://travis-ci.org/pywbem/pywbemtools/builds/584485943?utm_source=github_status&utm_medium=notification on which it failed at 50min in an earlier run.

**Comment by KSchopmeyer** [comment]
Note that in general the tests of pywbemcli take a long time.  I think that a lot of this is the call through the popen and load of the program which we are doing for almost every test. The two solutions I see are:

1. More tests in the interactive mode using stdin since that now works. The problem with this is that it is difficult to analyze results since you see the results of a bunch of commands rather than just a single command.

2. Go to using the inprocess mode for some testing we directly call the cli rather than running the whole popen. I assume that this would be significantly faster but have not created the environment to test if that is true.

**Comment by andy-maier** [comment]
The problem disappeared. See also https://github.com/pywbem/pywbem/issues/1862. Closing as no issue.
