### ISSUE TITLE
Consistency of prompting for user choice

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#349]
Currently, there are different ways how a user is prompted for a choice:
- 6 cases where operations on a single instance prompt for the instance to operate on. Triggered by option --interactive. Specified by passing a class name in the INSTANCENAME argument.
- 1 case where an operation on a connection definition prompts for the connection definition to operate on. Triggered by passing `?` for the NAME argument.

**COMMENT/KS** and two cases 'connection delete' and 'connect select' where the prompt is used if there is no NAME argument.  Note that in the connections group, the show is an outlier because it wants to take both the connections file and the current connection into account where select and delete only touch the connections file.

Can we define an approach that is more consistent than that?

**Comment by KSchopmeyer** [comment]
These cases are very different, they are not a general auto-completion mechanism.

1. INSTANCENAME - Goal was to simplify inputting INSTANCENAME by allowing select process to pick the name but requires  the CLASSNAME as a starting point. The selection process shows the instances are returns a valid one.

2. connection select/delete.  Allows alternative of selection if there is no NAME argument.. 'connection select' prompts but 'connection select blah' processes the name blah. The goal  is to act on a name in the connections file so the alternative of providing the NAME or nothing which activates the selection is easy.  In fact if TAB completion could be used in general we could simply have specified that (name or TAB autocomplete).  I cannot see any reason that adding an option here would help. This would be completly consistent with shell auto completion if we could use tab and if we could get to the list outside of pywbemcli.

3. The outlier to all this is "connection show".  The only reason for the ? option is because we really have 3 choices here we want the user to make since we want to be able to show 1) the current connection (connection show), 2) a named NAME argument connection(connection show blah) or 3) the list of existing connections(currently connection show ?. 

NOTE: I separate click autocomplete from bash autocomplete. There is a bash autocomplete for the static components (i.e options and choice type arguments. But I am not sure we could extend it to doing bash auto complete for connections in the connections file and I would really guess NO for getting instances of a class

IDEAS:

i mispoke in previous conversationabout the --interactive.  We could actually drop the interactive option and if only the class was provided (no keys) do the interaction because there are no singleton classes in CIM today or even to be sure create an instance name with no key and test it on the server.  Thus, the --interactive would disappear.  If the user supplied a class with no keys we would first try it as an instance name and if that failed, we would do the prompt for instance names.

If you wanted to make the user understand a bit better we could specify INSTANCENAME with the keys replaced by "?" instead of the --interactive so if the user specified instance get CIM_Blah.? that would be the signal for pywbemcli to prompt for the instance names.

So here are some alternatives:

1. Accept what we have for now.

2. Convert everything to --interactive.  

3. Convert everything to being able that you want prompted response from what is in the NAME argument 1. good name, or 2) partial name that pywbemcli could recognize as partial name (ex. empty in some cases or special char in some cases or special syntax (i.e no keys) in some cases.

I don't have a single answer here. But I really do not like the --interactive and would rather do it with the NAME/INSTANCENAME argument.

**Comment by andy-maier** [comment]
I like the idea to get rid of --interactive, i.e. your option 3. Another upside of a syntax like `CIM_Foo.?` is that we don't need to document that the INSTANCENAME argument in that case must be a CLASSNAME, but we can say it is still an instance name but one that triggers prompting. We could even transition this into tab completion lateron if we find out whether that can be done with click.

So my vote would be for 0.5.0:
* In the instance commands that have --interactive, use CLASSNAME.? to trigger prompting, and drop --interactive.
* In the connection commands that prompt for connection name when NAME is omitted, use ? to trigger the prompting. In cases where it makes sense, use the current connection as default; otherwise, NAME is required

In a future version, we can add support for tab completion for both connection names and instance names, after finding out how that can be done in Click. In instance names, the minimum input before tab completion would be done would be "CLASSNAME.". Then the tab completion can look up the instances of that class, like CLASSNAME.? also does.

**discussion needed** on this direction and staging.

**Comment by andy-maier** [comment]
In the last call, we agreed on the proposal from the previous comment.

**Comment by andy-maier** [comment]
PR #374 addresses this.
