### ISSUE TITLE
Issues with specifying and defaulting output format

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#354]
Note: Updated to reflect the discussion below.

Some commands ignore the specified output format without further notice, and change it to something else. An example is the `class find` command which honors table output formats (and seemingly also the txt format) but ignores all other output formats, using the txt format instead.

This is bad for the user, because they do not get any feedback that the output format they specified is not supported at all.

I suggest to change this as follows:
1. Every command has a reasonable default output format.
2. The specified output format is never changed to something else, but used as specified.
3. If the specified output format is not supported, the command fails, saying that.

**Comment by KSchopmeyer** [comment]
I am very uncomfortable with this.  Consider, for example that the default is MOF but we want to do class find.  That means that the user always have to change the output format to do a find.  Lets consider that the default format is the "recommended" one when it is available rather than a rigid set of rules.

We are trying to make it easy to get output that is usable rather that catch them in gotchas that causes them to have to redo command lines.

The alternative would be to force commands like find, count, etc. to be pure table output with no txt option.

**Comment by andy-maier** [comment]
I did not mean to suggest that there is only one single default for all commands. We can very well have a different default for each command, that suits its needs best. This means that the -o general option does not have a global default anymore, and its variable is set to None by default. This allows each command to set it to its command specific default if still None, and otherwise to check the specified format against the permitted formats for that command.

**Comment by andy-maier** [comment]
I think we can actually move this to 0.6.0. Changing this after the first release should be no big deal.

**Comment by andy-maier** [comment]
Updated the original description to reflect the discussion above, and further discussion in the meeting.

**Comment by andy-maier** [comment]
Addressed with PR #506

**Comment by andy-maier** [comment]
Karl wants to go through this to see what is left, after the PR has been merged.

**Comment by KSchopmeyer** [comment]
Done
