### ISSUE TITLE
"instance count" is not correct for subclasses

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#358]
See this example (mymock = -m tests/unit/simple_assoc_mock_model.mof):
```
$ pywbemcli --name mymock instance count
Count of instances per class
+------------------------------+---------+
| Class                        |   count |
|------------------------------+---------|
| TST_FamilyCollection         |       2 |
| TST_Lineage                  |       3 |
| TST_MemberOfFamilyCollection |       3 |
| TST_Person                   |       4 |
+------------------------------+---------+

$ pywbemcli --name mymock -o table instance enumerate TST_Person   
Instances: TST_Person
+------------+
| name       |
|------------|
| "Gabi"     |
| "Mike"     |
| "Saara"    |
| "Sofi"     |
| "Gabisub"  |
| "Mikesub"  |
| "Saarasub" |
| "Sofisub"  |
+------------+

$ pywbemcli --name mymock -o table instance enumerate TST_Personsub
Instances: TST_PersonSub
+------------+------------------+-----------+
| name       | secondProperty   |   counter |
|------------+------------------+-----------|
| "Gabisub"  | "four"           |         4 |
| "Mikesub"  | "one"            |         1 |
| "Saarasub" | "two"            |         2 |
| "Sofisub"  | "three"          |         3 |
+------------+------------------+-----------+
```

Issues:
1. TST_Personsub has 4 instances but is not reported in count
2. TST_Person has 8 instances if subclasses are counted, but 4 are reported. I actually find it desirable to list only the instances with that creation class, so this may well be perfectly ok if that was the intention.

**Comment by KSchopmeyer** [comment]
Yes it was the intention to list only the instances for that particular class, not for that class and subclasses. I thought I documented that.  In essence it just creates a count for each classname in the returned instances.  NOTE: I did find an issue from the output.  The column title should be count, not counter.  Further, in working with it a while ago, I also concluded that this would really be useful cross namespace like the find rather than just for a single namespace. Finally, I think that the name of the namespace(s) should be in the title, at least in the table form.  We are going to find more of these kinds of issues as we try to use the output data.

**Comment by andy-maier** [comment]
Ok, then I think the following is needed:
* clarify in docs that the classes listed are the creation classes, i.e. do not include subclass instances
* fix the bug of not showing the subclass instances I originally reported, above.
* Add namespace name as a column to the output table.

**Comment by andy-maier** [comment]
Adressed by PR #372
