### ISSUE TITLE
Add an indication listener to pywbemtools

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#430]
Goal: A command line mechanism that can listen for indications and account for them in multiple ways.

Basic requirements:
1. Ability to start and stop a particular listener in the command line environment.  Should be able to support multiple listeners on different ports simultaneously in the client cmd line environment
2. Ability to see the status of a listener (indications received, etc.)
3. (Optional) - Ability to filter received indications into different catagories for display, etc.

Some alternatives:

1. New tool that is a standalone listener. 
    a. Each listener started from the command line would have one listen port and defintion of disposition of results.  The listener would operate in the started process so that any use of multiple listeners would depend on the shell to start listeners in the background.  Normally termination would be simplistic through something like Ctro-C.
    b. A multi-port listener app that would allow the creation of multiple listeners in a single app with the actual listeners in the background.  The app would communicate requests for start, stop, status for each active listener.
   c. Add a listener group to pywbemcli that would allow control of multiple listeners in the background. Questions here include whether pywbemcli would have to be active during the life of the listeners or would they be independent processes?

Each listener should have the following basic controls:
 1. Start and stop
 2. Options for the destination of indications (display, log, count, pass to somewhere)
 3. request status of one or more listeners to get information  like (status, count, view indications received, etc.)

1. Command Group in pywbemcli that controls multiple listeners. A listener

**Comment by andy-maier** [comment]
DISCUSSION: Target release?

**Comment by KSchopmeyer** [comment]
We agree post 0.8.0

**Comment by andy-maier** [comment]
My vote would be that each started listener is a pywbemcli command that runs as a separate process, without having a managing pywbemcli command around. The "psutil" package can be used to deal with the processes. It supports all of our platforms and Python releases.

If we run the listeners as separate processes without having a managing pywbemcli command around, then it should also possible for a user to start the pywbemcli listener manually, i.e. without using a managing pywbemcli command.

Listing the listeners can be done by looking at the Python processes that have a command line matching a running pywbemcli listener. At the OS level, processes have a name. In case of the pywbemcli Python script, "Python" is the process name. The command line parameters of the Python process would need to be examined to find those that are pywbemcli invocations, and that could also be used to identify those pywbemcli invocations that are running listeners (as opposed to currently running other commands or interactive sessions). The psutil package supports access to the process command line, as a list of command line arguments.

I think each started listener should have a name that is used to control it. That is not the process name at the OS level, but would be something that is visible when listing the processes. The only thing for storing the name that comes to mind if we want to allow users to manually start listeners is the command line itself.

We also need something to manage subscriptions. Since a single listener can be the destination of multiple subscriptions from multiple WBEM servers, we need to decide whether the listener when run gets all the subscriptions passed and performs the subscriptions when starting, vs. having separate subscription management commands.

Proposal for the commands:
* `pywbemcli listener start --name NAME {run-options}` - start a pywbemcli listener under the name NAME using the specified run options
* `pywbemcli listener stop NAME` - stop pywbemcli listener process named NAME
* `pywbemcli listener run --name NAME {run-options}` - run as a listener under the name NAME using the specified run options
* `pywbemcli listener list` - list the running listeners (showing name, destination, count, filters?)
* `pywbemcli listener show NAME` - show the properties of a specific running listener

run-options:
* Options to set the destination, e.g. display, file, command, and probably also the format. Just counting can be achieved by not setting a destination.
* Options to filter indications (by inclusion and exclusion?).
* Options for subscribing to indications?

**Comment by andy-maier** [comment]
PR #971 (merged) adds the pywbemlistener command.

Since there are separate issues for docs and test, this issue is considered done:
* Tests: issue #981
* Docs: issue #980
