### ISSUE TITLE
Support for pywbem 1.0.0

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#504]
The master branch of pywbem (i.e. the upcoming pywbem 1.0.0) has changed some behavior so that some of the pywbemtools unit tests fail with it.

Running `make test` on the master branch of pywbemtools reports 50 failures when using pywbem from master (on MacOS with Python 2.7). This succeeds when using pywbem 0.16.0 from Pypi.

Among the failures are:
* ModelError: Namespace class could not be determined (tried ['CIM_Namespace', '__Namespace'])
* Unexpected WBEM URI (port is always shown in pywbem 1.0)
* pywbem 1.0 has more strict error checking when processing mock files
* Invalid port number in server URL is handled differently.
...

**Comment by KSchopmeyer** [comment]
Found issues.

find_class - Fails with ModelError.  This used to raise CIMError which we would just warn on but now raises ModelError which  kills that command.  This happens frequently in tests with the simple models like simplemock that has no interop namespace.

**Comment by andy-maier** [comment]
Addressed in PR #613. For now, the CI tests on the latest package version use the latest released pywbem 0.17.2. If and when a beta version of pywbem 1.0.0 gets released, the latest test will use that, so this is good enough for now.

**Comment by KSchopmeyer** [comment]
Issues have been resolved and submitted.  Since testing with 1.0.0 only local to date, I propose that this remain open until we release 1.0.0

This means that we are going to have to keep the minimum test against 0.17.0 or some 0.xx indefinitely to assure that pywbemcli supports earlier pywbem I assume to assure that we keep backward compatibility with pre 1.0.0 release.  Perhaps we should sort out a point where we stop guaranting backward compatibility to pywbem pre 1.0.
