### ISSUE TITLE
Support for getting operation statistics from the WBEM server (and statistics command group)

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#588]
Support getting operation statistics from the server (this was implemented in at least pegasus and j server).

Update: This issue started out to be just about the WBEM server stats but was extended to include the restructuring of how to display the statistics by means of adding a "statistics" command group.

The new issue #895 now covers adding the WBEM server side stats based on CIM_StatisticalData to the "statistics" command group.

**Comment by KSchopmeyer** [comment]
Need to clarify this one. We go get statistics from the wbem server if it is implemented and enabled in the server.  Note that we also get the server time (result passed in WBEMServerResponseTime). when the -T general option is set

However we do a really poor job of reporting this information since what we do is simply to report the statistics at the end of each operation.

I suggest that we should look at a more complex reporting mechanism but keep the -t --time_stats general option that enables the gathering.

We could add a command to the server to:

1. Report current statistics
2. Clear statistics in server.
3. enable or disable the display of statistics after each command.
4. 4. Try to enable or disable in the server (If the statistics exist in the server, there is a flag in a class in the server that enables or disables the gathering.  OpenPegasus enabled the client use of this with cimcli son and cimcli soff.  

The following is an example of statistics reported today 



```
pywbmcli -s http://localhost -T

pywbemcli> class enumerate PRS_Transaction --di --no
Statistics: Time(Seconds); Times/lengths: (Avg/Min/Max), single value if all same.
   Op    Exec  Op Time(S)         Server Time(S)     RequestLen     ReplyLen         Operation
  Cnt     Cnt  Avg/Min/Max        Avg/Min/Max        Avg/Min/Max    Avg/Min/Max
-----  ------  -----------------  -----------------  -------------  ---------------  -------------------
    2       0  0.024/0.005/0.043  0.001/0.001/0.001  371/332/411    31769/229/63309  EnumerateClassNames
    1       0  0.013              0.000              542            4187             GetClass

pywbemcli> class get CIM_ManagedElement
   [Abstract ( true ),
    Version ( "2.19.0" ),
    UMLPackagePath ( "CIM::Core::CoreElements" ),
    Description (
       "ManagedElement is an abstract class that provides a common superclass "
       "(or top of the inheritance tree) for the non-association classes in "
       "the CIM Schema." )]
class CIM_ManagedElement {


  . . .
};

Statistics: Time(Seconds); Times/lengths: (Avg/Min/Max), single value if all same.
   Op    Exec  Op Time(S)         Server Time(S)     RequestLen     ReplyLen         Operation
  Cnt     Cnt  Avg/Min/Max        Avg/Min/Max        Avg/Min/Max    Avg/Min/Max
-----  ------  -----------------  -----------------  -------------  ---------------  -------------------
    2       0  0.024/0.005/0.043  0.001/0.001/0.001  371/332/411    31769/229/63309  EnumerateClassNames
    2       0  0.010/0.007/0.013  0.000/0.000/0.000  542            4187             GetClass

pywbemcli>
Exception ignored in: <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 36666), raddr=('127.0.0.1', 5988)>
ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 36666), raddr=('127.0.0.1', 5988)>
(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools/pywbemtools/pywbemcli(ks/#588-support-wbemsvrstats)$

**Comment by KSchopmeyer** [comment]
We should support the server statistics on and off.  Note that in OpenPegasus this is a flag property in CIM_ObjectManager that the client must set to turn stats on.  That is part of the specs.  

We agreed that we want a more complete control of server statistics as part of pywbemcli
1. Turning on and off in server part of server
2. Controlliing the statistics should probably be a separate group.
