### ISSUE TITLE
A faster Mock loader would be nice

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#689]
I did a dry run of one of my scripts today and loading the Array mock took 22 seconds. This will only get worse as I add more profiles to the mock. It would be nice if we could reduce the load time.
This may be a pywbem thing, but I am seeing this using the pywbemcli.

**Comment by andy-maier** [comment]
I have opened https://github.com/pywbem/pywbem/issues/2365 for the needed improvements in pywbem.

**Comment by andy-maier** [comment]
The master branch of pywbem now has statistics support for the mock functions. The statistics are displayed using the already existing pywbemcli option `-T`.

What we need now, are statistics reports for some cases that are considered worthwhile improving, so we can learn where the time is spent.

**Comment by andy-maier** [comment]
Karl and I discussed this today, and believe that the outcome of any measurements will be that MOF compile is what consumes the time, and that caching the resulting repo would be what we need to go for.

We noted that it is not necessary to address the question of how to package profiles (i.e. issue #2409) in order to cache the repo, but we rather can do that at the level of the entire repo, as long as it is controlled by the connection definition as the top level handle to it.

@KSchopmeyer Karl, to confirm our expectation about where the time is spent, could you still please post some meaurements from the larger mock environment that you have access to?
