### ISSUE TITLE
Issues with pywbemcli statistics display

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#724]
If possible change to use the output display headers defined by pywbem.  Not tthe reason we use our own may be that we have the table tool available.

**Comment by andy-maier** [comment]
Example:
```
$ pywbemcli -n assoc -T class tree
root
 +-- TST_FamilyCollection
 +-- TST_Lineage
 +-- TST_MemberOfFamilyCollection
 +-- TST_Person
     +-- TST_Personsub
  Count    Exc  Time               ReqLen    ReplyLen    Operation
-------  -----  -----------------  --------  ----------  -------------------------
      1      0  0.040              0/inf/0   0/inf/0     compile_mof_file(ns=None)
      1      0  0.002              0         0           EnumerateClasses
      5      0  0.001/0.001/0.002  0         0           CreateClass
     16      0  0.001/0.001/0.001  0         0           CreateInstance
      7      0  0.000/0.000/0.000  0         0           SetQualifier
```

Pywbemcli with the `-T` option does not use `pywbem.Statistics.formatted()` to display the statistics, but instead just gets the data and formats it on its own.

There are multiple issues with this:
* There is no information about the units of the times and sizes
* The time is shown sometimes with all 3 values (avg,min,max) and sometimes just with a single value
* The sizes are shown sometimes with all 3 values (avg,min,max) and sometimes just with a single value
* The sizes for WBEM operations (which should produce non-zero sizes) are all 0
* The sizes are shown needlessly since all values are 0 (`pywbem.Statistics.formatted()` suppresses them if all 0), but that is a matter of taste I think. Probably it is better to show them always.
