### ISSUE TITLE
Test model qualifier_filter_model.mof error in Indication qualifier declaration

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#766]
The hand coded qualifier declaration for this test is incomplete.

**Comment by andy-maier** [comment]
The assertion error can be seen in pywbemtools PR https://github.com/pywbem/pywbemtools/pull/765: [Travis run](https://travis-ci.org/github/pywbem/pywbemtools/jobs/731487334)

Since a part of the problem seems to be originated in pywbem, issue https://github.com/pywbem/pywbem/issues/2458 had been opened.
