### ISSUE TITLE
Replace the help builder for docs 

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#94]
We initally created an tool that tries to build all of the help output into a coherent .rst file.  However this
has proven to be a continual pain so we need a new way to accomplish this.  There may be some new tools in click addons that will help.

**Comment by andy-maier** [comment]
Don't think that click provides tools for that, but I have not investigated it in depth.

We may want to consider using Jinja2 templates instead of hard coding it in the current click_help_capture.py tool. As of PR #100, the click_help_capture.py tool now runs also in Appveyor, so there is no urgent need anymore to address this.

**Comment by KSchopmeyer** [comment]
Complete 0.5.0. Andy rewrote tool
