### ISSUE TITLE
Need usable indication listener for test purposes

### ISSUE THREAD

**Issue by peter-lamanna** [pywbem/pywbemtools#948]
Working with customer who needs to have a working indication workflow.

**Comment by andy-maier** [comment]
I assume this request is about a command line tool? There is a usable listener in pywbem, but it requires programming to use it, in order to handle the indications that come in. And that is exactly the problem with a command line listener: What should it do with the indications? Displaying them? Having some way of passing them on to somewhere else?

**Comment by andy-maier** [comment]
Peter, we dicussed your request in our call today, and decided that we want to pursue this in the next release 1.0.0 as part of the already existing isue issue #430. I will close this issue as a duplicate of #430. Please make any comments on issue #430.
